# Generated by Django 5.2.13 on 2026-05-01 05:54

import LPS.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("PB", "Powerball"),
                            ("MM", "Mega Millions"),
                            ("LT", "Lotto Texas"),
                            ("TS", "Texas Two Step"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotteryDraw",
            fields=[
                ("draw_id", models.AutoField(primary_key=True, serialize=False)),
                ("draw_date", models.DateField()),
                ("winning_numbers", models.CharField(max_length=50)),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "draw_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("published", "Published"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draws",
                        to="LPS.lotteryticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PP", "PayPal"),
                            ("VN", "Venmo"),
                            ("BK", "Linked Bank Account"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        default=LPS.models.generate_confirmation_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase Confirmation"),
                            ("draw_result", "Draw Result"),
                            ("winner", "Winner"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "draw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="LPS.lotterydraw",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="LPS.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectronicTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=LPS.models.generate_ticket_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "lottery_type",
                    models.CharField(
                        choices=[
                            ("PB", "Powerball"),
                            ("MM", "Mega Millions"),
                            ("LT", "Lotto Texas"),
                            ("TS", "Texas Two Step"),
                        ],
                        max_length=2,
                    ),
                ),
                ("numbers", models.CharField(max_length=50)),
                ("winner", models.BooleanField(default=False)),
                (
                    "calculated_prize",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="LPS.lotterydraw",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="LPS.order",
                    ),
                ),
            ],
        ),
    ]
